name: PR linting
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  lint-pr:
    uses: ComPWA/actions/.github/workflows/pr-linting.yml@244cbdc9ef919cf659fcf26abeb04d6da39434ac # 4.1.1
